version: '3.4'

services:
  remixaboutme:
    image: remixaboutme
    build:
      context: application
      dockerfile: ../docker/npm/Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - ./application:/app
  redis:
    image: "redis:6.2.6-alpine3.15"
    container_name: cache
    ports:
      - "6379:6379"
    expose:
      - 6379
    restart: always

volumes:
  data:
